### ISSUE TITLE
CUDA Support?

### ISSUE THREAD

**Issue by cristian-vijelie** [unikraft/gsoc#1]
Maybe we could add CUDA / GPU support in Unikraft as a project. It is needed by applications that do AI / image processing.

**Comment by nderjung** [comment]
Thanks for the suggestion @cristian-vijelie!

To add to this, there is this off-stream related work which can be introduced/upstreamed/migrated/learned-from:

https://docs.vaccel.org/unikernels/unikraft/

**Comment by cristian-vijelie** [comment]
Maybe CUDA is a bit too ambitious, as Nvidia keeps its stuff hidden. But OpenCL would be interesting

**Comment by cristian-vijelie** [comment]
After some reading, this is not a project for 3 months. I'll close the issue

**Comment by cristian-vijelie** [comment]
After some reading, this is not a project for 3 months. I'll close the issue
